# Edit to add your credentials and save as config.yml
OPENAI_API_KEY: "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"
NEWSAPI_APP_ID: "994f9902"
NEWSAPI_APP_KEY: "9070bacf4915c9eb16cad8b78bf6fdae"
